name: 'Install relevant media software'

description: 'Install relevant media software'
runs:
  using: "composite"
  steps:
    - name: Setup latest updates
      shell: bash
      run: sudo apt update
    - name: Setup ImageMagick
      shell: bash
      run: sudo apt install imagemagick -y
    - name: Setup ffmpeg
      shell: bash
      run: sudo apt-get install ffmpeg -y
    - name: Setup Ghostscript
      shell: bash
      run: sudo apt-get install ghostscript -y