name: 'Build code and Sonar Analyze'
description: 'Build code and Sonar Analyze'
inputs:
  sonar_organization:
    description: 'Sonar Organization'
    required: true
  sonar_project_key:
    description: 'Sonar Project Key'
    required: true
  github_token:
    description: 'Github token'
    required: true
  sonar_token:
    description: 'Sonar token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Build - Clean Jacoco Verify
      shell: bash
      run: >
        mvn --batch-mode --update-snapshots
        clean
        org.jacoco:jacoco-maven-plugin:prepare-agent
        verify
        org.jacoco:jacoco-maven-plugin:report
    - name: Sonar Analyze
      shell: bash
      run: >
        mvn --batch-mode
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=${{ inputs.sonar_organization }}
        -Dsonar.projectKey=${{ inputs.sonar_project_key }}
        sonar:sonar
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
