name: CI

on:
  workflow_call:
    inputs:
      sonar_organization:
        description: 'Sonar Organization'
        required: true
        type: string
      sonar_project_key:
        description: 'Sonar Project Key'
        required: true
        type: string

    secrets:
      SONAR_TOKEN:
        required: true
      PERSONAL_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build - Clean Jacoco Verify
        run: >
          mvn --batch-mode --update-snapshots
          clean
          org.jacoco:jacoco-maven-plugin:prepare-agent
          verify
          org.jacoco:jacoco-maven-plugin:report
      - name: Sonar Analyze
        run: >
          mvn --batch-mode
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=${{ inputs.sonar_organization }}
          -Dsonar.projectKey=${{ inputs.sonar_project_key }}
          sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload all jars to target-jars
        uses: actions/upload-artifact@v3
        with:
          name: target-jars
          path: ./**/target/*.jar
          retention-days: 1
