name: DEPLOY ARTIFACTS

# REPOSITORY_USERNAME (maven)
# REPOSITORY_PASSWORD (maven)
on:
  workflow_call:

jobs:
  deploy_libraries:
    if: ${{ github.ref == 'refs/heads/develop' || contains(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest
    env:
      REPOSITORY_ID: artifactory.eanadev.org
      REPOSITORY_USERNAME: ${{ secrets.REPOSITORY_USERNAME }}
      REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Prepare Settings Deploy
        run: >
          mkdir -p ~/.m2 &&
          echo "<settings><servers><server><id>${REPOSITORY_ID}</id><username>${REPOSITORY_USERNAME}</username><password>${REPOSITORY_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
      - name: Deploy
        run: >
          mvn --batch-mode
          -Dmaven.test.skip=true
          -Dmaven.install.skip=true
          deploy