name: DEPLOY ARTIFACTS

on:
  workflow_call:
    secrets:
      ARTIFACTORY_USERNAME:
        required: true
      ARTIFACTORY_PASSWORD:
        required: true

jobs:
  deploy_libraries:
    if: ${{ github.ref == 'refs/heads/develop' || contains(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_ID: artifactory.eanadev.org
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
      - name: Prepare Settings Deploy
        run: >
          mkdir -p ~/.m2 &&
          echo "<settings><servers><server><id>${ARTIFACTORY_ID}</id><username>${ARTIFACTORY_USERNAME}</username><password>${ARTIFACTORY_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
      - name: Deploy
        run: >
          mvn --batch-mode
          -Dmaven.test.skip=true
          -Dmaven.install.skip=true
          deploy