
# target-jars pre-uploaded artifacts
on:
  workflow_call:
    inputs:
      docker-organization:
        description: 'Docker Organization'
        required: true
        type: string
      docker-image-name:
        description: 'Docker Image Name'
        required: true
        type: string
      project-path:
        description: 'Project Path'
        required: true
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    env:
      ORGANIZATION: ${{ inputs.docker-organization }}
      IMAGE_NAME: ${{ inputs.docker-image-name }}
      PROJECT_PATH: ${{ inputs.project-path }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: target-jars
      - name: Set dynamic environment variables for docker image tags
        run: |
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_ENV
          echo "GIT_REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --exact-match --tags HEAD)" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version --quiet -DforceStdout)" >> $GITHUB_ENV
      - name: Build Docker Image with tags
        run: |
          set -x
          docker build  \
          --tag ${ORGANIZATION}/${IMAGE_NAME}:${PROJECT_VERSION} \
          --tag ${ORGANIZATION}/${IMAGE_NAME}:${GIT_BRANCH} \
          --tag ${ORGANIZATION}/${IMAGE_NAME}:${GIT_REVISION} \
          --file ${PROJECT_PATH}/Dockerfile ${PROJECT_PATH}
          if [ ! -z "${GIT_TAG}" ]; then
            docker tag ${ORGANIZATION}/${IMAGE_NAME}:${PROJECT_VERSION} ${ORGANIZATION}/${IMAGE_NAME}:${GIT_TAG}
          fi
          set +x
      - name: Docker Login
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
      - name: Docker Push
        run: |
          set -x
          docker push ${ORGANIZATION}/${IMAGE_NAME}:${PROJECT_VERSION}
          docker push ${ORGANIZATION}/${IMAGE_NAME}:${GIT_BRANCH}
          docker push ${ORGANIZATION}/${IMAGE_NAME}:${GIT_REVISION}
          if [ ! -z "${GIT_TAG}" ]; then
            docker push ${ORGANIZATION}/${IMAGE_NAME}:${GIT_TAG}
          fi
          set +x
