name: DEPLOY ARTIFACTS

#Requires inherited secrets:
# IBM_CLOUD_API_ENDPOINT
# IBM_CLOUD_REGION
# IBM_CLOUD_API_KEY
# IBM_CLOUD_K8S_CLUSTER_NAME
on:
  workflow_call:

jobs:
  k8s-deploy:
    runs-on: ubuntu-latest

    env:
      IBM_CLOUD_API_ENDPOINT: ${{ secrets.IBM_CLOUD_API_ENDPOINT }}
      IBM_CLOUD_REGION: ${{ secrets.IBM_CLOUD_REGION }}
      IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
      IBM_CLOUD_K8S_CLUSTER_NAME: ${{ secrets.IBM_CLOUD_K8S_CLUSTER_NAME_TEST_ACCEPTANCE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f kubernetes-service
          ibmcloud plugin install -f container-registry
      - name: Prepare Cluster Config
        run: |
          ibmcloud login -a "${IBM_CLOUD_API_ENDPOINT}" -r "${IBM_CLOUD_REGION}" --apikey "${IBM_CLOUD_API_KEY}"
          ibmcloud ks cluster config --cluster "${IBM_CLOUD_K8S_CLUSTER_NAME}"
          ls -la ~/.kube
      - name: Set output kube config
        id: config
        run: echo "config=$(cat ~/.kube/config)" >> $GITHUB_OUTPUT